# 本文件采用 TOML 格式 https://toml.io/

# 文章标题 [请勿手动修改，会自动获取]
title = '''Organizing /Applications folder in macOS'''

# 文章作者 [通常留空，自动等同于博客作者]
author = ''''''

# 文章创建时间
ctime = '2024-03-15 15:48:39+00:00'

# 文章修改时间
mtime = '2024-03-17 21:59:01+00:00'

# sha1, 用来判断文章内容有无变更 [请勿手动修改]
checksum = '155b3dbc8f8a256075433bbd68f6dd31ac67c10d'

# 是否忽略文章 (true/false)
# 被忽略的文章不会出现在最近列表、索引列表里，但仍会出现在 RSS 里
ignored = false

# HTML中的图片的最大宽度 (留空表示跟随总设定)
img_width = ''

# 是否执行自动替换 (0:跟随总设定, -1:不执行, 1:执行)
replace = 0

# 自动替换。例:
# pairs =  [
#   [ '''../output/pics/abc.jpg''', '''https://example.com/abc.jpg''' ],
#   [ '''../output/pics/def.jpg''', '''https://example.com/def.jpg''' ],
# ]
pairs = [

]

# 文章摘要
abstract = '''I struggle sometimes with hundreds of apps installed in my Applications.'''

summary = '''The article addresses organizing a cluttered macOS Applications folder. Using Alfred for common apps works well, but finding less frequently used apps is challenging due to non-descriptive icons and names. The author suggests categorizing apps like iOS's App Library and notes issues with moving apps, including broken functionalities. They recommend creating a '~/Applications' folder for app aliases to prevent these problems, using automation tools like Hazel for maintenance. This method facilitates finding apps without altering the original Applications folder, suitable for users overwhelmed by their app collection but unnecessary for those with fewer apps or who prefer minimal organization.
'''