# 本文件采用 TOML 格式 https://toml.io/

# 文章标题 [请勿手动修改，会自动获取]
title = '''Setting up Globus endpoint for your servers'''

# 文章作者 [通常留空，自动等同于博客作者]
author = ''''''

# 文章创建时间
ctime = '2023-06-16 16:12:43+01:00'

# 文章修改时间
mtime = '2023-07-09 00:10:04+01:00'

# sha1, 用来判断文章内容有无变更 [请勿手动修改]
checksum = '6fa6d0f0602df66a7c98d5eecd5bf54c7d17f9b8'

# 是否忽略文章 (true/false)
# 被忽略的文章不会出现在最近列表、索引列表里，但仍会出现在 RSS 里
ignored = false

# HTML中的图片的最大宽度 (留空表示跟随总设定)
img_width = ''

# 是否执行自动替换 (0:跟随总设定, -1:不执行, 1:执行)
replace = 0

# 自动替换。例:
# pairs =  [
#   [ '''../output/pics/abc.jpg''', '''https://example.com/abc.jpg''' ],
#   [ '''../output/pics/def.jpg''', '''https://example.com/def.jpg''' ],
# ]
pairs = [

]

# 文章摘要
abstract = '''
With Globus, you can easily, reliably and securely move, share, & discover data no matter where it lives – from a supercomputer, lab cluster, tape archive, public cloud or laptop.'''
summary = '''Setting up a Globus endpoint on your servers allows for easy and secure data management across various storage systems. To do this, log in to your cluster with X11 forwarding, install Globus Connect Personal, and initiate it in CLI mode. Upon receiving a login URL and completing authorization in your web browser, you label the endpoint for future reference. Adjust the config-paths to access other directories like $SCRATCH. Starting the client on the cluster will activate your endpoint, enabling data transfer via the Globus web interface. For continuous background operation, use the `nohup` command. To stop the service, kill the process using its PID.'''
