# 本文件采用 TOML 格式 https://toml.io/

# 文章标题 [请勿手动修改，会自动获取]
title = '''Hoarder - The Self-Hosted Bookmark Manager'''

# 文章作者 [通常留空，自动等同于博客作者]
author = ''''''

# 文章创建时间
ctime = '2024-05-24 18:56:37+01:00'

# 文章修改时间
mtime = '2024-11-07 14:57:21+00:00'

# sha1, 用来判断文章内容有无变更 [请勿手动修改]
checksum = '741ff769d20d60754d7a6242373b3987af56092a'

# 是否忽略文章 (true/false)
# 被忽略的文章不会出现在最近列表、索引列表里，但仍会出现在 RSS 里
ignored = false

# HTML中的图片的最大宽度 (留空表示跟随总设定)
img_width = ''

# 是否执行自动替换 (0:跟随总设定, -1:不执行, 1:执行)
replace = 0

# 自动替换。例:
# pairs =  [
#   [ '''../output/pics/abc.jpg''', '''https://example.com/abc.jpg''' ],
#   [ '''../output/pics/def.jpg''', '''https://example.com/def.jpg''' ],
# ]
pairs = [

]

# 文章摘要
abstract = '''Trying out Hoarder app today, to see whether it would competes Anybox as my main bookmark manager. I do like self-hosting services.
At first sight, it feels like a complete app I can put in production, it has a iOS app with share sheet support, chrome exte...'''

summary = ''''''