# 本文件采用 TOML 格式 https://toml.io/

# 文章标题 [请勿手动修改，会自动获取]
title = '''My App Defaults'''

# 文章作者 [通常留空，自动等同于博客作者]
author = ''''''

# 文章创建时间
ctime = '2023-11-09 21:30:40+00:00'

# 文章修改时间
mtime = '2023-11-09 22:50:40+00:00'

# sha1, 用来判断文章内容有无变更 [请勿手动修改]
checksum = '65874f5d8ff0192cf90e2f935c768cc3b2df8184'

# 是否忽略文章 (true/false)
# 被忽略的文章不会出现在最近列表、索引列表里，但仍会出现在 RSS 里
ignored = false

# HTML中的图片的最大宽度 (留空表示跟随总设定)
img_width = ''

# 是否执行自动替换 (0:跟随总设定, -1:不执行, 1:执行)
replace = 0

# 自动替换。例:
# pairs =  [
#   [ '''../output/pics/abc.jpg''', '''https://example.com/abc.jpg''' ],
#   [ '''../output/pics/def.jpg''', '''https://example.com/def.jpg''' ],
# ]
pairs = [

]

# 文章摘要
abstract = '''My App Defaults inspired by Hemispheric Views 097 - Duel of the Defaults!'''

summary = ''''''