# 本文件采用 TOML 格式 https://toml.io/

# 文章标题 [请勿手动修改，会自动获取]
title = '''RSS-GPT 使用指南'''

# 文章作者 [通常留空，自动等同于博客作者]
author = ''''''

# 文章创建时间
ctime = '2023-09-11 17:51:18+01:00'

# 文章修改时间
mtime = '2023-09-12 10:15:00+01:00'

# sha1, 用来判断文章内容有无变更 [请勿手动修改]
checksum = '5afbc857dcf0a2f9a05d66e91e5dc5dee5304300'

# 是否忽略文章 (true/false)
# 被忽略的文章不会出现在最近列表、索引列表里，但仍会出现在 RSS 里
ignored = false

# HTML中的图片的最大宽度 (留空表示跟随总设定)
img_width = ''

# 是否执行自动替换 (0:跟随总设定, -1:不执行, 1:执行)
replace = 0

# 自动替换。例:
# pairs =  [
#   [ '''../output/pics/abc.jpg''', '''https://example.com/abc.jpg''' ],
#   [ '''../output/pics/def.jpg''', '''https://example.com/def.jpg''' ],
# ]
pairs = [

]

# 文章摘要
abstract = '''项目地址与功能介绍

yinan-c/RSS-GPT
RSS-GPT介绍
English manual

需要准备的东西

GitHub 账号
OpenAI API Key （可以在这里建立账号申请）

1 GitHub Actions 部署
大致原理是使用 GitHub Actions 定时运行 Python 脚本,...'''