# 本文件采用 TOML 格式 https://toml.io/

# 文章标题 [请勿手动修改，会自动获取]
title = '''AI 总结 RSS Feeds'''

# 文章作者 [通常留空，自动等同于博客作者]
author = ''''''

# 文章创建时间
ctime = '2023-09-07 14:21:35+01:00'

# 文章修改时间
mtime = '2023-09-29 19:19:18+01:00'

# sha1, 用来判断文章内容有无变更 [请勿手动修改]
checksum = '0159099e973850ead922b4d7200131b551b12f71'

# 是否忽略文章 (true/false)
# 被忽略的文章不会出现在最近列表、索引列表里，但仍会出现在 RSS 里
ignored = false

# HTML中的图片的最大宽度 (留空表示跟随总设定)
img_width = ''

# 是否执行自动替换 (0:跟随总设定, -1:不执行, 1:执行)
replace = 0

# 自动替换。例:
# pairs =  [
#   [ '''../output/pics/abc.jpg''', '''https://example.com/abc.jpg''' ],
#   [ '''../output/pics/def.jpg''', '''https://example.com/def.jpg''' ],
# ]
pairs = [

]

# 文章摘要
abstract = '''如何用 AI 帮助你阅读 RSS Feeds。'''

summary = '''本文介绍了如何利用RSS-GPT工具优化RSS订阅体验，通过关键词过滤和内容总结减少信息过载。作者表达了对RSS作为信息获取工具的喜爱，同时也提到了没有筛选的RSS容易导致信息过载，给用户带来焦虑。文章介绍了如何使用关键词过滤和内容摘要功能来解决这个问题，特别推荐了RSS-GPT工具，该工具能够对RSS订阅源进行全文总结和关键词提取，帮助用户快速了解文章主要内容，决定是否深入阅读。最后，作者提供了配置RSS-GPT的教程，希望能够帮助更多用户改善他们的RSS订阅体验。'''
