# 本文件采用 TOML 格式 https://toml.io/

# 文章标题 [请勿手动修改，会自动获取]
title = '''RSS-GPT Configuration'''

# 文章作者 [通常留空，自动等同于博客作者]
author = ''''''

# 文章创建时间
ctime = '2023-09-11 18:14:50+01:00'

# 文章修改时间
mtime = '2023-10-18 01:17:57+01:00'

# sha1, 用来判断文章内容有无变更 [请勿手动修改]
checksum = '5f8fe41ad02eb865443488914452bf1ee7d86f26'

# 是否忽略文章 (true/false)
# 被忽略的文章不会出现在最近列表、索引列表里，但仍会出现在 RSS 里
ignored = false

# HTML中的图片的最大宽度 (留空表示跟随总设定)
img_width = ''

# 是否执行自动替换 (0:跟随总设定, -1:不执行, 1:执行)
replace = 0

# 自动替换。例:
# pairs =  [
#   [ '''../output/pics/abc.jpg''', '''https://example.com/abc.jpg''' ],
#   [ '''../output/pics/def.jpg''', '''https://example.com/def.jpg''' ],
# ]
pairs = [

]

# 文章摘要
abstract = '''How to configure RSS-GPT, using AI to summarize your RSS feed.'''
summary = '''The RSS-GPT tool uses GitHub Actions to automatically generate summaries for RSS feeds using the OpenAI API, and commits a new XML file to the user's GitHub repo. Users can access this feed through GitHub Pages or the raw XML file URL. The process involves forking the RSS-GPT project, setting repository secrets, and configuring the desired RSS sources and filters in `config.ini`. Users can modify the Python script `main.py` and test the setup via GitHub Actions. The system defaults to using GPT-3.5 Turbo for cost-efficiency but can be adjusted for other models. It's designed for easy updates and customization of summaries without repeated API calls for existing articles.'''
