# 本文件采用 TOML 格式 https://toml.io/

# 文章标题 [请勿手动修改，会自动获取]
title = '''RSS-GPT Configuration'''

# 文章作者 [通常留空，自动等同于博客作者]
author = ''''''

# 文章创建时间
ctime = '2023-09-11 18:14:50+01:00'

# 文章修改时间
mtime = '2023-09-13 15:19:23+01:00'

# sha1, 用来判断文章内容有无变更 [请勿手动修改]
checksum = 'e803ad612c7705ffd3523ae26945d3914ae99018'

# 是否忽略文章 (true/false)
# 被忽略的文章不会出现在最近列表、索引列表里，但仍会出现在 RSS 里
ignored = false

# HTML中的图片的最大宽度 (留空表示跟随总设定)
img_width = ''

# 是否执行自动替换 (0:跟随总设定, -1:不执行, 1:执行)
replace = 0

# 自动替换。例:
# pairs =  [
#   [ '''../output/pics/abc.jpg''', '''https://example.com/abc.jpg''' ],
#   [ '''../output/pics/def.jpg''', '''https://example.com/def.jpg''' ],
# ]
pairs = [

]

# 文章摘要
abstract = ''' A detailed configuration guide for RSS-GPT, a script that uses ChatGPT to summarize your personalized RSS feeds. '''