# 本文件采用 TOML 格式 https://toml.io/

# 文章标题 [请勿手动修改，会自动获取]
title = '''Separating tasks and non-actionable items'''

# 文章作者 [通常留空，自动等同于博客作者]
author = ''''''

# 文章创建时间
ctime = '2023-09-20 17:20:56+01:00'

# 文章修改时间
mtime = '2023-11-04 15:41:59+00:00'

# sha1, 用来判断文章内容有无变更 [请勿手动修改]
checksum = '2164eb76e840a0f06ae28534560cd8a8833e9318'

# 是否忽略文章 (true/false)
# 被忽略的文章不会出现在最近列表、索引列表里，但仍会出现在 RSS 里
ignored = false

# HTML中的图片的最大宽度 (留空表示跟随总设定)
img_width = ''

# 是否执行自动替换 (0:跟随总设定, -1:不执行, 1:执行)
replace = 0

# 自动替换。例:
# pairs =  [
#   [ '''../output/pics/abc.jpg''', '''https://example.com/abc.jpg''' ],
#   [ '''../output/pics/def.jpg''', '''https://example.com/def.jpg''' ],
# ]
pairs = [

]

# 文章摘要
abstract = '''Some thoughts on task management.'''

summary = '''This article explores the author’s shift in task management strategy, emphasizing the importance of separating actionable tasks and non-actionable items. Previously cluttered with both types of items, the author now uses Things 3 exclusively for tasks and Devonthink for notes, documents, and readlist items. This approach, inspired by a discussion on the MPU forum, aims to maintain a clean and focused task manager, while non-actionable items are sorted and stored in Devonthink. The author highlights the issue of a rapidly filling inbox in Things 3 and proposes his new strategy as an effective solution, ultimately aiming for a clearer mind and more efficient workflow.'''