# 本文件采用 TOML 格式 https://toml.io/

# 文章标题 [请勿手动修改，会自动获取]
title = '''Setup SSH keys for GitHub and remote servers'''

# 文章作者 [通常留空，自动等同于博客作者]
author = ''''''

# 文章创建时间
ctime = '2023-07-01 19:55:37+01:00'

# 文章修改时间
mtime = '2023-07-09 00:25:49+01:00'

# sha1, 用来判断文章内容有无变更 [请勿手动修改]
checksum = 'c1495cf6ca51c8b15cf357ec08dbc5c375b73f38'

# 是否忽略文章 (true/false)
# 被忽略的文章不会出现在最近列表、索引列表里，但仍会出现在 RSS 里
ignored = false

# HTML中的图片的最大宽度 (留空表示跟随总设定)
img_width = ''

# 是否执行自动替换 (0:跟随总设定, -1:不执行, 1:执行)
replace = 0

# 自动替换。例:
# pairs =  [
#   [ '''../output/pics/abc.jpg''', '''https://example.com/abc.jpg''' ],
#   [ '''../output/pics/def.jpg''', '''https://example.com/def.jpg''' ],
# ]
pairs = [

]

# 文章摘要
abstract = '''A step-by-step guide to setup SSH keys for GitHub and remote servers.'''

summary = '''This article provides a detailed guide on setting up SSH keys for GitHub and remote servers, highlighting the security benefits of using SSH keys for secure remote communication. It describes two main methods: using ssh-keygen and the 1Password SSH agent, providing step-by-step instructions and configuration guidelines for both. Additionally, the article emphasizes the importance of protecting keys with a passphrase and recommends using 1Password for managing SSH keys and other sensitive information. References for further reading and documentation are also provided.'''
