# 本文件采用 TOML 格式 https://toml.io/

# 文章标题 [请勿手动修改，会自动获取]
title = '''苹果端 Todo App 简单比较'''

# 文章作者 [通常留空，自动等同于博客作者]
author = ''''''

# 文章创建时间
ctime = '2024-05-22 00:32:57+01:00'

# 文章修改时间
mtime = '2024-05-22 11:24:22+01:00'

# sha1, 用来判断文章内容有无变更 [请勿手动修改]
checksum = '6d40ead7fb5f7dd3c5479a21978066cd1f46cfe2'

# 是否忽略文章 (true/false)
# 被忽略的文章不会出现在最近列表、索引列表里，但仍会出现在 RSS 里
ignored = false

# HTML中的图片的最大宽度 (留空表示跟随总设定)
img_width = ''

# 是否执行自动替换 (0:跟随总设定, -1:不执行, 1:执行)
replace = 0

# 自动替换。例:
# pairs =  [
#   [ '''../output/pics/abc.jpg''', '''https://example.com/abc.jpg''' ],
#   [ '''../output/pics/def.jpg''', '''https://example.com/def.jpg''' ],
# ]
pairs = [

]

# 文章摘要
abstract = '''继半年多前从 Things 转移到 OmniFocus 之后，今天又在探索几大 TODO App，主要比较了 Things, OmniFocus 以及 TickTick。
Things
先说说老朋友 Things，Logbook 显示我从2022年的7月开始用到了2023年的11月15日，等...'''

summary = ''''''